<a href="https://colab.research.google.com/github/sabinamunoz/lab-feature-engineering/blob/master/lab_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('/content/drive/MyDrive/IronHack Bootcamp/UNIT 7/learningSet.csv', dtype = {'NOEXCH': str})
df

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0.0,0,L,2,G,X,X,X,1.0,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,1,L,4,E,X,X,X,60.0,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,1,L,4,E,X,X,X,41.0,C
4,8601,,0,FL,33176,,,2001,0,X,...,0.0,1,L,2,F,X,X,X,26.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,ASE,1,AK,99504,,,0,0,,...,0.0,0,L,1,G,X,X,X,12.0,C
95408,9601,DCD,1,TX,77379,,,5001,0,,...,0.0,1,L,1,F,X,X,X,2.0,A
95409,9501,MBC,1,MI,48910,,,3801,0,,...,0.0,1,L,3,E,X,X,X,34.0,B
95410,8601,PRV,0,CA,91320,,,4005,0,X,...,18.0,1,L,4,F,X,X,X,11.0,A
95411,8801,MCC,2,NC,28409,,,1801,0,X,...,0.0,1,L,1,G,C,1,C,12.0,C

##**1. Check for null values in numerical columns**

In [ ]:
num_cols = df.select_dtypes(np.number)

In [16]:
nulls = pd.DataFrame(num_cols.isna().sum(), columns=['nan_count'])
nulls = nulls[nulls['nan_count'] > 0]
nulls.sort_values('nan_count', ascending = False)

          nan_count
RDATE_5       95403
RAMNT_5       95403
RAMNT_3       95170
RDATE_3       95170
RDATE_4       95131
...             ...
ADATE_3        1950
MSA             132
ADI             132
DMA             132
CLUSTER2        132

[91 rows x 1 columns]

##**2. Clean GEOCODE2, WEALTH1, ADI, DMA and MSA**

In [17]:
print(df['WEALTH1'].value_counts().isna().sum())
df['GEOCODE2'].value_counts()

0

A    34484
B    28505
D    16580
C    15524
       187
Name: GEOCODE2, dtype: int64

In [18]:
df.loc[(df["GEOCODE2"] == " "), "GEOCODE2"] = 'A'
df['GEOCODE2'].value_counts()

A    34671
B    28505
D    16580
C    15524
Name: GEOCODE2, dtype: int64

In [ ]:
# no cleaning necessary. according to data description wealth is bucketed into groups 0-9
print(df['WEALTH1'].value_counts().isna().sum())
df['WEALTH1'].value_counts()

0

9.0    7585
8.0    6793
7.0    6198
6.0    5825
5.0    5280
4.0    4810
3.0    4237
2.0    4085
1.0    3454
0.0    2413
Name: WEALTH1, dtype: int64

###**Columns ADI, DMA and MSA are codes, according to data description**

In [ ]:
#
print(df['ADI'].value_counts().isna().sum())
df['ADI'].value_counts().sort_index()

0

0.0       843
3.0        29
9.0        68
11.0       25
13.0     7296
         ...
621.0     118
625.0      63
627.0      28
645.0     257
651.0       1
Name: ADI, Length: 204, dtype: int64

In [ ]:
# most values in 500-800 range, with the exception of 0 (187 rows)
print(df['DMA'].value_counts().isna().sum())
df['DMA'].value_counts().sort_index()

0

0.0       187
500.0       8
501.0      68
502.0       2
503.0     245
         ...
855.0     413
862.0    1847
866.0     582
868.0     345
881.0     640
Name: DMA, Length: 206, dtype: int64

In [ ]:
# large amount of 0 values (21k in 95k total), indicating they could be nulls transformed into zeros
print(df['MSA'].value_counts().isna().sum())
df['MSA'].value_counts()

0

0.0       21333
4480.0     4606
1600.0     4059
2160.0     2586
520.0      1685
          ...
9140.0        1
3200.0        1
9280.0        1
743.0         1
8480.0        1
Name: MSA, Length: 298, dtype: int64